// <auto-generated>
// This file is generated from HostContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate.
// </auto-generated>

/**
 * Represents a named presentation cue that is currently active on an object.
 */
export interface HostCommandActiveObjectPresentationCue {
  /** Catalog key identifying the active presentation cue. */
  effectKey: string;
  /** Stable identifier retained while this cue activation remains active. */
  activationId: string;
}
